version: '3.8'
services:
  elsticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - 9200:9200
    environment:
      DISCOVERY_TYPE: single-node
    restart: on-failure

  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
      - 5601:5601
    depends_on:
      - elsticsearch
    restart: on-failure

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.7.0
    volumes:
      -
  jms:
    image: vromero/activemq-artemis
    ports:
      - 8161:8161
      - 61616:61616
    restart: on-failure

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    restart: on-failure

  eureka:
    image: sfgbeerworks/sfg-brewery-eureka
    ports:
      - 8761:8761
    restart: on-failure

  config:
    image: sfgbeerworks/sfg-brewery-config
    ports:
      - 8888:8888
    depends_on:
      - eureka
    restart: on-failure